/**
 * Post-processes the Astro build output for display in the CircleCI artifact viewer.
 *
 * Astro emits processed assets (images, JS bundles) at absolute paths like `/_astro/...`.
 * In the artifact viewer these resolve to the domain root rather than the artifact
 * directory, so every reference must be prefixed with the full artifact base path.
 *
 * Navigation links and CSS references use relative paths (generated by fromSiteRoot),
 * so they already resolve correctly inside the artifact tree and need no changes.
 *
 * Usage:
 *   node scripts/circleci-preview.mjs <artifact-base-path>
 *
 * Example (CircleCI):
 *   node scripts/circleci-preview.mjs \
 *     "/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/html"
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const artifactBase = process.argv[2];
if (!artifactBase) {
  console.error(
    "Usage: node scripts/circleci-preview.mjs <artifact-base-path>",
  );
  process.exit(1);
}

/** @param {string} dir */
function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (entry.isFile() && full.endsWith(".html")) {
      patch(full);
    }
  }
}

/**
 * Rewrites every `/_astro/` reference in an HTML file to use the artifact base.
 * Handles double-quoted, single-quoted, and unquoted CSS url() contexts.
 * @param {string} file
 */
function patch(file) {
  let content = readFileSync(file, "utf8");

  // `/_astro/` appears in src="", href="", srcset="", url(), and inline <script> strings
  content = content.replaceAll(`"/_astro/`, `"${artifactBase}/_astro/`);
  content = content.replaceAll(`'/_astro/`, `'${artifactBase}/_astro/`);
  content = content.replaceAll(`(/_astro/`, `(${artifactBase}/_astro/`);

  writeFileSync(file, content);
}

walk("html");
console.log(`Patched /_astro/ paths with base: ${artifactBase}`);
